#+TITLE: Algebra
#+AUTHOR: Vittorio Zaccaria
#+LEVEL: 3
#+OPTIONS: H:3

* Algebraic structures with one operator
** Other structures 
*** Magma
    A magma is set $M$ equipped with a single binary operation,
    $(*): M \times M \rightarrow M$ that satisfies:

   - *closure*: $a \in M, b \in M \rightarrow a * b \in M$ 

** Monoids
*** Monoid
   
   A monoid $(M,*)$ is a *semigroup* with a unit element ($1 \in M$) where the $*$ 
   operation satisfies:
   
   - *identity*: $a * 1 = a, \forall a \in M$.

*** Generator set (Monoid)
    A subset $S$ of $M$ is said to be a generator if all elements $y \in M$ 
    can be obtained by some kind of *fold* of the elements $x \in S$.

    \[
      \forall y \in M, \exists a_1, \ldots, a_n \in S \textrm{~~s.t.~~} y = a_1 * \cdots * a_n
    \]

*** Free generator set (Monoid)
    A subset $S$ of $M$ is said to be a free generator if all elements $y \in M$ 
    can be obtained by a *unique fold* of the elements $x \in S$:

    \[
      \forall y \in M, \exists a_1, \ldots, a_n \in S \textrm{~~s.t.~~} y = a_1 * \cdots * a_n
    \]

    Not all generator sets are free. For example, $\{1\}$ is a generator for
    $\mathbb{Z}_n$ but it is not free, in the sense that each element of
    $\mathbb{Z}_n$ can be defined by multiple sequences of 1.

*** Free monoid

    - A free monoid is a monoid *with a free generator*.

    - Example: $(\mathbb{N}, +)$ is the *free monoid generated by 1*.

*** Abelian monoid
    A monoid $(M,*)$ where $$\forall a,b \in M, a * b = b * a$$

*** Monoid homomorphisms 
    Given two monoids $(X,\star)$ and $(Y, *)$, a homomorphism $$f: (X,\star)
    \rightarrow (Y,*)$$ is a function $f: X \rightarrow Y$ such that:
    
    \[
      f(1_X) = 1_Y \textrm{~~and~~} f(m \star n) = f(m) * f(n)
    \]

** Groups
*** Group
   
   A [[https://en.wikipedia.org/wiki/Group_(mathematics)][group]] $G$ is a monoid where for all elements $a$, the (*) operation satisfies:

   - *closure*: $a \in G, b \in G \rightarrow a * b \in G$
   - *identity element*: $a * 1_G = 1_G * a = a$
   - *invertibility*: $a * a^{-1} = 1$.
   - *associativity*: $a * (b * c) = (a * b) * c$ 

   In a group, every element has its own inverse.

*** Subgroup  
   $H$ is a [[https://en.wikipedia.org/wiki/Subgroup][subgroup]] of $G$ if:

   - it is a subset of $G$ 
   - it forms a group under the operation (*).

   The *trivial subgroup* of any group is the subgroup ${e}$ consisting of just the identity element.

*** Normal subgroup
    $H$ is a normal subgroup of $G$ iff $$\forall a \in H \wedge x \in G, xax^{-1} \in H$$.

*** Kernel of a group homomorphism
    The *kernel* of a homomorphism $f: G \rightarrow H$ is a subset $K$ where
    all the elements $k \in K$ map into the unit of $H$:
    $$ \textrm{ker}(f) = \{ x \in G: f(x) = 1_{*} \}$$

*** Range of a group homomorphism
    The *range* of a homomorphism $f: G \rightarrow H$ is a subset $L$ of $H$
    where $$\textrm{range}(f) = \{ l \in L:  \exists g \in G \textrm{~s.t.~} l = f(g) \}$$

*** Coset 
    Given a subgroup $H$ and some $a$ in $G$, we define the *left coset* of $H$ as
    $$H_a = \{ah : h \in H\}$$ 

*** What is the set of cosets of a normal subgroup $H$ of $G$?

    It is a partition of $G$ and it is a group where the operation is defined as $$Ha + Hb = H(a+b)$$


*** Subgroup of an abelian group
    Every subgroup of an abelian group is normal.

*** Coset multiplication
    
    Coset multiplication operation: $Ha * Hb = H(ab),~~a,b \in G$. 

*** Factor/quotient group

    - If $H$ is a normal subgroup of $G$, coset multiplication is a group
      operation of a particular group: the *factor (or quotient) group*.

    - The factor group $G/H$ is a group where elements are the
      cosets of $G$ by $H$ and group operation is cosets multiplication.
  
*** Construct a quotient group $Z/6Z$. 
    

    - $H = 6Z$ is the subgroup of all multiples of 6 in $Z$
    - *elements* of the quotient group are all the unique cosets $$H_a = \{ 6Z + a, a \in Z \}$$
      (their elements are infinite, but there are only 6 of them, $H_1=H_7=\ldots$).
    - the *operation* among cosets $$H_a + H_b = H_{a + b}$$  respects
      the quotient group properties.
    
    This quotient group is also called *the cyclic group $Z_6$*. 

*** Homomorphisms of a group into a quotient group 
    Given a quotient group $G/H$, there is a homomorphism $G \rightarrow G/H$.

*** How many elements has each coset of $H$ (a subgroup of $G$)?
    
    All cosets of $H$ have *the same amount* of elements of $H$ 

*** What is the size of a group $G$ with respect to the size of the cosets of its subgroup $H$?

    The size of $G$ is a multiple of the size of $H$ (and in turn, also of the size of its cosets).
    
*** Semigroup 
   
    A [[https://en.wikipedia.org/wiki/Semigroup][semigroup]] $S$ is a "group without inverse".

   - *closure*: $a \in G, b \in G \rightarrow a * b \in G$
   - *identity element*: $a * 1_G = 1_G * a = a$
   - *associativity*: $(a * b) * c = a * (b * c),~~a,b,c \in G$.



*** Group identity and inverse properties

    Both the identity and the inverse of every element are *unique*.

*** Endomorphism ring of an abelian group

    Given a group $(A,+)$, we can define a set F of group homomorphisms:
    \[
      F = End(A) = \{ f: f(a + b) = f(a) + f(b), \forall a,b \in A \}
    \]
    
    $End(A,++,\circ, \textrm{const~} 0, \textrm{const~} 1)$ is a *ring* (of functions) where

    - $(f ++ g)(x) = f(x) + g(x)$
    - $(f \circ g)(x) = f(g(x))$

*** Order of a group element
    In a group, the least integer $n$ such that $a^n=1_{*}$, then that element 
    has order $n$.

*** Cyclic group
    If $G$ has an element $a$ and all its elements are powers of $a$, then $G$ is cyclic:
    $$G = \{ a^n : n \in Z \}$$

    $a$ is called generator and the group order is the order of $a$. 
    
*** Symmetric group 
    The symmetric group $S_n$ is the group of all permutations (symmetries) of $\{1, . . . , n\}$

*** Group action
     
     - A group action $\phi$ of group $G$ on a set $X$ is a function 
       $$*: G \times X \rightarrow X$$ satisfying the following properties:

       - identity: $e * x = x$
       - compatibility: $(gh) * x = g * (h * x)$

     - An action $g * x$ is the same as a group homomorphism $G \rightarrow \textrm{Aut}(X)$

*** Linear group representation
    
    - A *linear group representation* of $G$ is a group homomorphism 
      $$\rho : G \rightarrow GL(V)$$
     
    - It “represents” the elements of $G$ as *symmetries of the vector space $V$*.

*** Permutation representation of $G$ on $X$
     The *permutation representation* encodes a group $G$ action on $X$ as a
     linear group representation on $V$ which is built on bases indexed by
     $X$.

     It is defined as the group homomorphism $$\rho: G \rightarrow
     GL(V)$$ given by $$\rho(s)e_{x}=e_{s.x}$$

*** Left regular representation 

    - If we treat $G$ as a set $X$, the left regular representation is just the 
      permutation representation of $G$ on $G$.

    - Formally, we can assign a vector basis to each $g \in G$ to get a vector
      space $\mathbb{C}G$ that is freely generated by the elements of $G$.
 
    - A left regular representation $$G \rightarrow
      GL(\mathbb{C}G)$$ represents a left translation by $g$ (i.e., one of 
      the possible actions}.

*** Right regular representation 

    - If we treat $G$ as a set $X$, the right regular representation is defined
      by a different permutation representation of $G$ on $G$, i.e.,
      $$\rho(s)e_{x}=e_{x.s^{-1}}$$

# # *** Group representation 

# #     A group representation is a function $$\rho : G \rightarrow E \rightarrow E$$
# #     with the following properties:

# #     - $E$ is a vector space
# #     - $\rho(gh) = \rho(g)\rho(h)$ (homomorphism)
# #     - $\rho(1)v = v$
# #     - $(g*_Gh)v = g(hv)$
    
# #     where $g,h \in G$, $v \in E$.

# # *** Degree of a representation

# #     The degree of a representation of $G$ over $V$ is the *dimension of its
# #     representation space* $V$.




    
* Algebraic structures with two operators
** Semirings
*** Semiring (Rig)
    A [[https://en.wikipedia.org/wiki/Semiring][semiring]] $R$ consists of a set $R$ such that:

    - $(R, +)$ is a commutative monoid with identity = 0 (note, *not a group*, it
      should not have an inverse).
    - $(R, *)$ is a monoid with identity = 1
    - multiplication distributes over addition
    - multiplication by 0 gives 0 (annihilates).
   
** Rings 
*** Ring

    A [[https://en.wikipedia.org/wiki/Ring_(mathematics)][ring]] $R$ consists of a set $R$ such that:
    
    - $(R, +)$ is a *commutative* *group* with identity=0 (note that it should have
      an inverse).
    - $(R, *)$ is a monoid with identity = 1 (Semigroup)
    - multiplication distributes over addition
    - multiplication by 0 gives 0 (annihilates).

*** Ideals 
    An *ideal* $I$ is a special subset of a ring $R$ that respects the following properties:

    - *closure*: $*: I \times I \rightarrow I$ is total.
    - *absorption*: $+:I \times R \rightarrow I$ is total.

    Example: the even numbers are an ideal of the natural numbers

*** Ring homomorphism

    If $R$ and $S$ are rings, a ring homomorphism $f: R \rightarrow S$ is a
    total function such that: 

    - $f(a + b) = f(a) + f(b)$
    - $f(a * b) = f(a) * f(b)$
    - $f(1_R) = 1_S$


** Fields

*** Field

    A [[https://en.wikipedia.org/wiki/Field_(mathematics)][field]] a set with two operations:

    - $(F, +)$ is a commutative group 
    - $(F, *)$ is a commutative group 

*** Field characteristic 

    Given a multiplication operator 

    \[ 
      \cdot: \mathbb{N}^+ \times F \rightarrow F = \sum_{n} f, ~~f \in F
    \] 

    The field characteristic $n$ is such that $n \cdot 1_{*}$ is 0. 
    If $n \neq 0$, then $n$ is prime, otherwise it is 0.

*** Prime field F
    A finite field of order $p$ where $p$ is prime.

*** Finite field $F_p$
    It has $p$ elements. If $p$ is prime then $F_p$ is a prime field and
    operations are understood as modular.

*** What field is isomorphic to rational numbers?
    Every field with characteristic 0 has a subfield isomorphic to rational
    numbers


* Algebras of vector spaces and modules
** Vector spaces 

*** Vector space

    A pair $(V,K)$ where 

    - $(K,(+,0),(\cdot,1))$ is a field
    - $(V,+,e)$ is an abelian group under addition
    
    Moreover, the following operation should be total (scalar multiplication)
    \[
    *: K \times V \rightarrow V
    \]

*** Simple vectors

    They are ordered sequences of elements that belong to a field ([[https://en.wikipedia.org/wiki/Scalar_(mathematics)][scalars)]].
    Classical results of geometry apply.

*** Normed vector spaces
    
    A *normed* vector space $V$ is endowed with a map $V \rightarrow R$. 

*** Inner product spaces 
    
    An *inner product* space $V$ is endowed with an operation $V \times V \rightarrow R$.

*** Algebra 

    - It is a module/vector space equipped with a bi-linear operator $$ \times: V \times V
      \rightarrow V$$ acting as *multiplication* between vectors.

    - The following axioms should hold:

      - Right distributivity: $(x + y) \times z = x \times z + y \times z$
      - Left distributivity: $x \times (y + z) = x \times y + x \times z$
      - Compatibility with scalars: $(ax) \times (by) = (ab) (x \times y)$.

    - Examples: 
    
      - $R^3$ with cross-product $\times$

*** Linear map

    It is a mapping between modules/vector spaces $V \rightarrow W$ that
    preserves addition and scalar multiplication.

*** R-Module

    Generalization of vector space. A pair $(V,K)$ where 

    - $(K,(+ ,0),(\cdot,1))$ is a *ring*
    - $(V,+,e)$ is an abelian group under addition
    
    Moreover, the following operation should be total (scalar multiplication)
    \[
    *: K \times V \rightarrow V
    \]
  
   
