#+TITLE: Algebra
#+AUTHOR: Vittorio Zaccaria
#+LEVEL: 3
#+OPTIONS: H:3

* Algebraic structures with one operator
** Other structures
*** Magma
    A magma is set $M$ equipped with a single binary operation,
    $(*): M \times M \rightarrow M$ that satisfies:

   - *closure*: $a \in M, b \in M \rightarrow a * b \in M$

** Monoids
*** Monoid

   A monoid $(M,*)$ is a *semigroup* with a unit element ($1 \in M$) where the $*$
   operation satisfies:

   - *identity*: $m * 1 = m, \forall m \in M$.

*** Generator set (Monoid)
    A subset $S$ of $M$ is said to be a generator if all elements $m \in M$
    can be obtained by some kind of *fold* of the elements $s \in S$.

    \[
      \forall m \in M, \exists s_1, \ldots, s_n \in S \textrm{~~s.t.~~} m = s_1 * \cdots * s_n
    \]

*** Free generator set (Monoid)

    A subset $S$ of $M$ is said to be a generator if all elements $m \in M$
    can be obtained by a *unique fold* of the elements $s \in S$.

    \[
      \forall m \in M, \exists s_1, \ldots, s_n \in S \textrm{~~s.t.~~} m = s_1 * \cdots * s_n
    \]

    Not all generator sets are free. For example, $\{1\}$ is a generator for
    $\mathbb{Z}_n$ but it is not free, in the sense that each element of
    $\mathbb{Z}_n$ can be defined by multiple sequences of 1.

*** Free monoid

    - A free monoid is a monoid *with a free generator*.

    - Example: $(\mathbb{N}, +)$ is the *free monoid generated by 1*.

*** Abelian monoid
    A monoid $(M,*)$ where $$\forall m_1,m_2 \in M, m_1 * m_2 = m_2 * m_1$$

*** Monoid homomorphisms
    Given two monoids $(X,\star)$ and $(Y, *)$, a homomorphism $$f: (X,\star)
    \rightarrow (Y,*)$$ is a function $f: X \rightarrow Y$ such that:

    \[
      f(1_X) = 1_Y \textrm{~~and~~} f(m \star n) = f(m) * f(n)
    \]

** Groups
*** Group

   A [[https://en.wikipedia.org/wiki/Group_(mathematics)][group]] $G$ is a monoid where for all elements $a$, the (*) operation satisfies:

   - *closure*: $a \in G, b \in G \rightarrow a * b \in G$
   - *identity element*: $a * 1_G = 1_G * a = a$
   - *invertibility*: $a * a^{-1} = 1$.
   - *associativity*: $a * (b * c) = (a * b) * c$

   In a group, every element has its own inverse.

*** Subgroup
   $H$ is a [[https://en.wikipedia.org/wiki/Subgroup][subgroup]] of $G$ if:

   - $H \subseteq G$
   - It is closed under (*).

   The *trivial subgroup* of any group is the subgroup ${e}$ consisting of just the identity element.

*** Normal subgroup
    $H$ is a normal subgroup of $G$ iff $$\forall h \in H \wedge g \in G, ghg^{-1} \in H$$

*** Kernel of a group homomorphism
    The *kernel* $\textrm{ker}(f)$ of a group homomorphism $f: (G,\star)
    \rightarrow (H,*)$ is a set $K$ such that

    - $K \subseteq G$
    - $\forall k \in K, f(k) = 1_{*}$

*** Range of a group homomorphism
    The *range* $\textrm{range}(f)$ of a homomorphism  $f: (G,\star)
    \rightarrow (H,*)$ is a set $R$ such that

    - $R \subseteq H$
    - $\forall r \in R, \exists g \in G \textrm{~s.t.~} r = f(g)$

*** Coset
    Given a subgroup $(H, \star) \subseteq (G, \star)$, we define the *left coset* of $H$ as
    $$H_g = \{g \star h : h \in H\}$$

*** What is the set of cosets of a normal subgroup $H$ of $G$?

    It is a partition of $(G, \star)$ and it is a group where the operation is defined as
    $$Hg_1 \star Hg_2 = H(g_1 \star g_2)$$


*** Subgroup of an abelian group
    Every subgroup of an abelian group is normal.

*** Coset multiplication

    Coset multiplication operation: $$Hg_1 * Hg_2 = H(g_1 \star g_2),~~g_1,g_2 \in G$$

*** Factor/quotient group

    - If $H$ is a normal subgroup of $G$, coset multiplication is a group
      operation of a particular group: the *factor (or quotient) group*.

    - The factor group $G/H$ is a group where elements are the
      cosets of $G$ by $H$ and group operation is cosets multiplication.

*** Construct a quotient group $Z/6Z$.


    - $(G, +) = Z$
    - $(H, +) \subseteq (G,+) = 6Z$ is the subgroup of all multiples of 6 in $Z$
    - *elements* of the quotient group are all the unique cosets $$H_g = \{ 6Z + g, g \in Z \}$$
      (their elements are infinite, but there are only 6 of them, $H_1=H_7=\ldots$).
    - the *operation* among cosets $$Hg_1 + Hg_2 = H_{g_1 + g_2}$$  respects
      the quotient group properties.

    This quotient group is also called *the cyclic group $Z_6$*.

*** Fundamental homomorphism theorem

    - Given a quotient group $G/H$, there is a homomorphism $\mu: G \rightarrow G/H$.

    - Given any homomorphism $\phi: G \rightarrow Q$ with its kernel $H$, $Q$ is
      always isomorphic to $G/H$.


*** How many elements has each coset of $H$ (a subgroup of $G$)?

    All cosets of $H$ have *the same amount* of elements of $H$

*** What is the size of a group $G$ with respect to the size of the cosets of its subgroup $H$?

    The size of $G$ is a multiple of the size of $H$ (and in turn, also of the size of its cosets).

*** Semigroup

    A [[https://en.wikipedia.org/wiki/Semigroup][semigroup]] $S$ is a "group without inverse".

   - *closure*: $a \in G, b \in G \rightarrow a * b \in G$
   - *identity element*: $a * 1_G = 1_G * a = a$
   - *associativity*: $(a * b) * c = a * (b * c),~~a,b,c \in G$.



*** Group identity and inverse properties

    Both the identity and the inverse of every element are *unique*.

*** Endomorphism ring of an abelian group

    Given a group $(G,+,0_G)$, we can define a set
    \[
      End(G) = \{ f: G \rightarrow G | f(a + b) = f(a) + f(b) \}
    \]

    The set $End(G)$ can be made into a *ring* with the following
    operations/properties

    - sum: $(f ++ g)(x) = f(x) + g(x)$
    - sum unit: $f = x \mapsto 0$
    - sum inverse: $f^{-1}x = (f x)^{-1}$
    - multiplication: $(f \circ g)(x) = f(g(x))$
    - multiplication unit: $f = x \mapsto x$

*** Order of a group element
    In a group, the least integer $n$ such that $a^n=1_{*}$, then that element
    has order $n$.

*** Cyclic group
    If $G$ has an element $a$ and all its elements are powers of $a$, then $G$ is cyclic:
    $$G = \{ a^n : n \in Z \}$$

    $a$ is called generator and the group order is the order of $a$.

*** Symmetric group
    The symmetric group $S_n$ is the group of all permutations (symmetries) of $\{1, . . . , n\}$

*** Group action

     - A group action $\phi$ of group $G$ on a set $X$ is a function
       $$*: G \times X \rightarrow X$$ satisfying the following properties:

       - identity: $e * x = x$
       - compatibility: $(gh) * x = g * (h * x)$

     - An action $g * x$ is the same as a group homomorphism $G \rightarrow \textrm{Aut}(X)$

*** Commutator subgroup

   - A commutator subgroup $[G,G]$ is an abelian group that can be built from a
     finite group $G$.

   - It is composed of the set of elements $$[G,G] = \{ xyx^{-1}y^{-1}, x~y \in G \}$$

   - It is a normal subgroup

*** Commutator subgroup of $S_n$

    The commutator subgroup of $S_n$ is the alternating group $A_n$. It
    is the set of all even permutations in $S_n$. Even = even number of
    transpositions in which it can be written.

*** Subgroup index

    The index of a subgroup H in G is defined as the number of cosets of H in G.

** Group representations
*** Linear group representation

    - A *linear group representation* of $G$ is a group homomorphism
      $$\rho : G \rightarrow Aut(V)$$

    - It represents the elements of $G$ as *symmetries of the vector space* $V$.

    - By choosing a basis in $V$, $Aut(V) \simeq GL(V)$.

*** Properties of a linear group representation

    - $\rho_g \rho_h = \rho_{gh}$
    - $\rho_1 = Id$
    - $(\rho_g)^{-1} = \rho_{g^{-1}}$
    - $\rho_g(xv + yw) = x\rho_gv + y\rho_gw$

*** Permutation representation
     - The *permutation representation* is associated with a symmetric group $G =
       S_n$ and acts on a $V_k = k^n$.

     - Assume $v \in V_k = \sum_j a_j e_j$ with e_j basis. A permutation
       representation $\rho_{\pi}: S_n \rightarrow GL(k^n)$ is such that $\rho_s
       v = \sum a_j e_{s(j)}$.

     - Practically speaking, gives a permutation matrix for each $g \in G$.

*** Character of a representation

    The *character* of a representation $\rho$ is the trace of the corresponding
    matrix: $\chi_{\rho_g} = Tr(\rho_g)$.

*** Sign representation
    Given any representation of the permutation group $\rho(S_n)$,
    $\textrm{det}(\rho(S_n))$ is the corresponding sign representation as well
    and it is either 1 or -1.

*** Faithful representation

    A *faithful* representation $\rho$ is an *injective* map, i.e., different $g$
    are represented by distinct $\rho(g)$.

*** Unitary representations

    - Assume $V$ is a space equipped with a hermitian dot product (on $C_2$)
      that measures the distance between vectors (i.e., an Hilbert space).

    - $(\rho,V)$ is unitary (or, a unitary operator) if it preserves the
      distance of vectors ($\langle\rho(g)v,\rho(g)w\rangle = \langle v,w
      \rangle$).

    - If the group is finite, then one can always build an unitary operator.

    - See [[[https://en.wikipedia.org/wiki/Unitary_representation#Complete_reducibility][complete reducibility of unitary representations]]].

*** Trivial representation

    - A representation $\rho: G \rightarrow GL(E_k)$ is trivial if all $g \in G$
      map to an identity matrix.

*** Invariant representation
     A representation $\rho(g)$ is *invariant* if $\forall v \in V \rho(g)v \subseteq V$

*** Intertwining operator

  - An intertwining operator is a functor $\Phi_{ij}: E_i \rightarrow E_j$ that
    preserves representations: $$\Phi_{ij}(\rho_i(g)v)=\rho_j(g)\Phi_{ij}(v)$$.

  - As such, it introduces a homomorphism between representations $$\rho_2
    = \Phi_{12} \rho_1$$ which comply with composition.

  - We can thus say that any group $G$ defines a *category of representations* and
    we can speak of its morphisms (intertwiner) as $Hom_G(\rho_1, \rho_2)$.

*** Equivalence of representations

  $\rho_1, \rho_2$ are equivalent if there exists an intertwining operator $L$
  that has an inverse and such that $$L \circ \rho_1 = \rho_2 \circ L$$.

*** Subrepresentations
   Given a subspace $F \subseteq E$, if $$\forall f \in F, ~~\rho(G)(f) \in
     F$$ then $(\rho, F)$ is a *subrepresentation* of $(\rho, E)$.

*** Trivial subrepresentation

   - A trivial subrepresentation $(\rho, E)$ is such that $\rho(g)e = e$.

   - in fact, $E^G$ is isomorphic to $Hom_G(1,E)$, i.e., the space of constant functions
     over $E$.

*** Irreducible representation

    An *irreducible* representation $(\rho,V)$ has as subrepresentations only
    $(\rho,0)$ and $(\rho,V)$

*** Maschke's theorem
    Any representation of $(\rho: G \rightarrow V_k)$ is a direct sum of
    irreducible pieces (constituents) if $|G|$ is not a multiple of $char(k)$.
*** Full reducibility

    If $V = W_1 \oplus \ldots W_n$ and all $(\rho, W_i)$ are irreducible then
    $(\rho, V)$ is fully reducible.

*** Representations of Abelian groups

    - For an abelian group, it is possible to choose a basis to make $\rho(g)$ diagonal.

    - For G finite, matrices are going to be block diagonal.

*** One dimensional representation

  - A one-dimensional $k$ representation is built above a homomorphism $\chi: G
    \rightarrow k^{\times}$ and corresponds to a representation $\rho_k(g) =
    \chi(g)Id_{V}$ ($\chi(\cdot)$ is in fact a scalar).

  - The set $\hat{G}$ of one-dimensional representations of a group $G$ is an
    abelian group and it is isomorphic to $G/G'$ where $G'$ is the
    commutator subgroup.

*** Representations of external direct sums

   - An external direct sum $V \oplus V'$ is the set of pairs that can be built

   - $\rho_{\oplus}(g)(v,v') = (\rho(g)v, \rho'(g)v')$

   - Practically, if we concatenate $v,v'$ in a single vector, $\rho_{\oplus}$
     is a diagonal block matrix of $\rho, \rho'$.

*** Representations of dual spaces

    Given $(\rho,V)$, one can define a representation of its dual vector space
    $(\rho^*, V^*)$ such that $$\rho^*(g) f = f \circ \rho^{-1}(g)$$.

*** Representation of quotient spaces

    Assume $\mu: E \rightarrow E/W$ the canonical map of $E$ into its quotient
    vector space. Given a representation $(\rho, E)$, we can define
    $(\rho_{E/W}, E/W)$ such that $$\rho_{E/W}(g)q = \rho(g)v' \wedge \mu v' = q, q \in E/W$$.

*** Representation of a tensor product space

    Given $(\rho, V)$ and $(\rho', V')$, one can define
    $$(\rho_{\otimes},V \otimes V') = \rho v \otimes \rho' v'$$

    If input repr. are one-dimensional, tensoring becomes multiplication.

*** Representation of $Hom$ spaces

    Given $Hom_C(V, V') = \{ f: V \rightarrow V' \}$ linear, one can define
    a representation from representations of $V$ and $V'$:

    $$\rho_{Hom} f = \rho' \circ f \circ \rho^{-1}$$

*** Representation of conjugate vector spaces
    Given $(\rho,V)$, $\rho$ is a representation of the
    conjugate vector space $\bar{V}$ as well.

    A conjugate representation $(\rho, \bar{V})$ is *equivalent* to $(\rho, V)$
    and to its dual representation $(\rho^*, V^*)$.

*** Regular representation of $G$

    A group algebra $K[G]$ is a vector space of elements $\phi$ that can be written as
    $$\phi: \phi(g_1)g_1 + \phi(g_2)g_2 + \ldots$$ i.e., $$K[G]=span\{g_1, g_2,
    \ldots \}$$ The regular representation $(\rho_{K}, K[G])$ is such that
    $$\rho_{K}(s)\phi = \rho_{K}(s) \phi(g_1)g_1 + \ldots = \phi(g_1)(s*g_1) +
    \ldots$$

*** Regular representation of $G$ through Cayley

    - By Caley, there is an isomorphism $\rho_C: G \rightarrow S_n$ for a group
      $G$ of order $n$ that is given by picking a permutation $\lambda x.gx$.

    - A regular representation is just the concatenation of a permutation
      representation and the cayley isomorphism: $$\rho = \rho_{\pi} \circ
      \rho_{C}$$ In practice, it associates a permutation to each $g \in G$.

    - For example, the regular representation of a cyclic group of order $n$
      ($\{1,x,x^2,\ldots, x^n\}$) associates to each element the power of a
      cyclic permutation matrix $P$.

*** Representation of function space over $G$

    A function space $F(G) = \{ \phi: G \rightarrow K \}$ can be seen as composed
    of members of the group algebra (similarly to the Z-transform): $$\phi:
    \phi(g_1)g_1 + \phi(g_2)g_2 + \ldots$$ i.e., $$K[G]=span\{g_1, g_2, \ldots
    \}$$ thus one can define a representation that is equivalent to the group
    algebra's one.

*** Shur's lemma
     - If $(\rho, V)$ and $(\rho', V)$ are irreducible representations and there
       is an intertwining operator $L$, *then* $$L \neq 0 \rightarrow L
       \textrm{~is an equivalence}$$ (no middle ground).
*** Shur's lemma - corollary for $L : V \rightarrow V$
     For irreducible representations ($\rho,V$) all intertwining
     operators $L: V \rightarrow V$ have the form $L=\lambda I$.
*** Shur's lemma - corollary for $L_1, L_2$ intertwining operators
     For irreducible representations ($\rho, V$) and ($\rho', V'$) all the intertwining
     operators have the form $L_1 = \lambda L_2$.
*** Irreducible representations of abelian groups
    - All irreducible representations $(\rho, V)$ of an abelian group are such that
      $dim(V)=1$ (by Shur's lemma), i.e., they are one dimensional.
    - To each $\rho(g)$ it corresponds a scalar $\lambda_g$, which is called *character*.
    - If $\rho$ is not irreducible, then there exists a basis such that
      $\rho(g)$ is diagonal.
* Algebraic structures with two operators
** Semirings
*** Semiring (Rig)
    A [[https://en.wikipedia.org/wiki/Semiring][semiring]] $R$ consists of a set $R$ such that:

    - $(R, +)$ is a commutative monoid with identity = 0 (note, *not a group*, it
      should not have an inverse).
    - $(R, *)$ is a monoid with identity = 1
    - multiplication distributes over addition
    - multiplication by 0 gives 0 (annihilates).

** Rings
*** Ring

    A [[https://en.wikipedia.org/wiki/Ring_(mathematics)][ring]] $R$ consists of a set $R$ such that:

    - $(R, +)$ is a *commutative* *group* with identity=0 (note that it should have
      an inverse, so we can talk about *negative* values).
    - $(R, *)$ is a monoid with identity = 1 (Semigroup)
    - multiplication distributes over addition
    - multiplication by 0 gives 0 (annihilates).

*** Commutative ring

   A commutative ring $R$ is commutative if $(R, *)$ is commutative.

*** Ring divisor of zero
    - $a \neq 0$ is called divisor of zero if there is $b \neq 0$ such that $ab = 0$

    - Z,Q,R and C do not have divisors of zero. This means that, if the product
      of two numbers is zero, then one of them should be zero.

*** Ring cancellation property

    - A ring has cancellation property if and only if it doesn't have divisors
      of zero. Equationally: $$ ab = ac
      \rightarrow b = c $$

*** Integral domain
    - It is a commutative ring (with multiplication commutative) that has the
      cancellation property.

    - An integral domain with non-zero characteristic $p$ is such that $p$ is prime.

*** Integral domains and fields

    - Every field is an integral domain.

    - Every *finite* integral domain is a field, because you can find a
      multiplicative inverse for each element of the field (this depends on the
      fact that there are no zero divisors).

    - A *finite integral domain* is just a *finite field*


*** Quaternions

    - Quaternions are a subring of 2x2 matrices with unity.

    - Each quaternion $\alpha$ has a multiplicative inverse $(1/t)\bar{\alpha}$,
      where $\bar{\alpha}$ is its conjugate and $t$ is its norm.

*** Subring

    If $S \subseteq R$ ($R$ is a ring) and $S$ is closed under sum, difference
    and multiplication of $R$, then it is a subring of $R$.

*** Ideals
    A subring $I$ of $R$ if

    - it absorbs elements of $R$ by multiplication: $$\forall s \in I, \forall r
      \in R. sr \in I$$
    - it is closed under addition.

*** Principal ideal

    A /principal ideal/ can be generated by taking an element $s$ of a commutative
    ring $R$ and computing the set $$ \langle s \rangle = \{ s * r: r \in R \}$$

    It can be shown that it respects the ideal properties (closed under addition
    and difference and absorbs multiplication).



*** Ring homomorphism

    If $R$ and $S$ are rings, a ring homomorphism $f: R \rightarrow S$ is a
    total function such that:

    - $f(a + b) = f(a) + f(b)$
    - $f(a * b) = f(a) * f(b)$
    - $f(1_R) = 1_S$

*** Cosets of an ideal of a ring

    A coset of an ideal $I_a$, just as those of subgroups, is created with the
    addition operation as in group theory: $$I_a = \{ a + i | i \in I\} a \in
    R$$ We can define both addition and multiplication:

    - $I_a + I_b = I_{a + b}$
    - $I_a * I_b = I_{a * b}$

*** Quotient ring

    Given a ring $R$ and an ideal $I$, the set of cosets of $I$ is a ring and
    it is called the quotient ring $R/I$.

** Fields

*** Field

    A [[https://en.wikipedia.org/wiki/Field_(mathematics)][field]] a set with two operations:

    - $(F, +)$ is a commutative group
    - $(F, *)$ is a commutative group

*** Field characteristic

    A field has characteristic $n$ if $1_{*}$ summed with it self $n$ times gives
    $0_{+}$.

    The following relation is found to hold: $$ n > 0 \leftrightarrow
    \textrm{prime}(n)$$

*** Prime field F
    A finite field of order $p$ where $p$ is prime.

*** Finite field $F_p$
    It has $p$ elements. If $p$ is prime then $F_p$ is a prime field and
    operations are understood as modular.

* Algebras of vector spaces and modules
** Vector spaces

*** Vector space

    A pair $(V,K)$ where

    - $(K,(+,0),(\cdot,1))$ is a field
    - $(V,+,e)$ is an abelian group under addition

    Moreover, the following operation should be total (scalar multiplication)
    \[
    *: K \times V \rightarrow V
    \]

*** Simple vectors

    They are ordered sequences of elements that belong to a field ([[https://en.wikipedia.org/wiki/Scalar_(mathematics)][scalars)]].
    Classical results of geometry apply.

*** Direct sum

    The direct sum of two vector spaces is a linear combination (span) of their basis.

    $$V_1=span_k([0,1]), V_2=span_k([1,0]), V_1 \oplus V_2 = span_k([0,1],[1,0])$$

*** Normed vector spaces

    A *normed* vector space $V$ is endowed with a map $V \rightarrow R$.

*** Inner product spaces

    An *inner product* space $V$ is endowed with an operation $V \times V \rightarrow R$.

    Hermitian products are one of the possible operations

*** Dual Space

    - Given $V$, one can define its dual space as $V^* = \{f: V \rightarrow C
      \}$ where $f$ is a linear mapping.


*** Tensor product spaces

    Given two vector spaces $(V,V')$, I can define their tensor product $W =V
    \otimes V'$ by

    - creating monomials (concatenations) of their bases $e_i \otimes e'_j$ as
      a new basis for $W$

    - expressing the product $v \otimes v' = \sum_{c_{ij}}c_{ij} e_i \otimes e'_j$ such
      that the properties of a bilinear product hold.

*** Conjugate vector spaces

    Given a vector space on complex numbers $V_C$ then also $\bar{V}_C$, where
     scalar multiplication is $\bar{z}*v$ for $z \in C$, is a vector space.

*** Algebra

    - It is a module/vector space equipped with a bi-linear operator $$ \times: V \times V
      \rightarrow V$$ acting as *multiplication* between vectors.

    - The following axioms should hold:

      - Right distributivity: $(x + y) \times z = x \times z + y \times z$
      - Left distributivity: $x \times (y + z) = x \times y + x \times z$
      - Compatibility with scalars: $(ax) \times (by) = (ab) (x \times y)$.

*** Affine space
    - A tuple $(A, V_k, (+): V_k \times A \rightarrow A)$ defines an /affine space/
      $A$ if $(+)$ complies with the group action properties.
    - Alternatively, it can be defined as $(A, V_k, (-): A \times A \rightarrow V_k)$ where
      $(-)$ complies with Weyl's axioms

*** Quotient space
    Given a vector space $V$ and a subspace $W$, the quotient space $V/W$ is the set of
    cosets $W_v = \{ v + w | w \in W \}$.  Fixed a $v$, the coset represents the elements $y$
    for which $\exists w \in W, x - y = w$ which is an equivalence class.

*** Group Algebra as formal sum

    A group algebra $K[G]$ for a group $G$ and a field $K$ is a vector space
    that is the direct sum of copies of $K$ indexed by $G$.

    In practice, the basis $e_g$ is a vector that has a dimension $|G|$ and
    whose $g-th$ component is 1.

    Each element of the algebra is thus a formal linear combination of the
    elements of $G$ with coefficients in $K$, i.e., $$f = \sum_{g\in G}a_{g,f}
    e_g$$ where $e_g$ are basis in $K[G]$.


*** Group Algebra as function space

    Given a group $G$ and a field $K$, we can build an algebra $K[G]$ where

    - vectors are functions $f: G \rightarrow K$ for $K$ either a ring or
      field.
    - $(f_1 + f_2) = g \mapsto f_1(g) + f_2(g)$
    - $(\alpha f) = g \mapsto \alpha f(g)$
    - $(f_1 \times f_2) = g \mapsto \sum_{u \in G}f_1(u)f_2(u^{-1}g)$



*** R-Module

    Generalization of vector space. A pair $(V,K)$ where

    - $(K,(+ ,0),(\cdot,1))$ is a *ring*
    - $(V,+,e)$ is an abelian group under addition

    Moreover, the following operation should be total (scalar multiplication)
    \[
    *: K \times V \rightarrow V
    \]
* Category theory basics

** Category basics
*** Category

A category is a triple $\mathcal{C}(O, M, \bullet)$ that abides these laws:

- *identity*: $\forall o \in O, \exists id_o \in M$

- *composition*: '$\bullet$' composes morphisms in $M$ that share source and target :

  1. $\bullet(A \rightarrow B, B \rightarrow C) = A \rightarrow C$

  2. $(f \bullet g) \bullet h == f \bullet (h \bullet g)$

  3. $id_x \bullet f = f \bullet id_y$

** Monoid (Category)

*** Monoid as a category
    - A monoid $\mathcal{M}(M, id_0, \star)$ is just a category $\mathcal{C}(O, M, \star)$ where O = $\{ o_1 \}$ and $id_0 = id_{o1}$.

    - The elements $M$ of a monoid are the morphisms $M$ of the corresponding
      category. As such, *associativity* holds.

*** Free Monoid
:PROPERTIES:
:placement: 18,0
:END:

- A free monoid of M is just a monoid $\mathcal{M}(List[G], [], ++)$

- It has a free generator set G and all its elements are uniquely determined by
  a fold of elements in $G$.

*** Action

An action of a $\mathcal{M}(M, id_0, \star)$ over a set $S$ of states is a
function  \[ \alpha: M \times S \rightarrow S \]. The following properties should be satisfied:

- identity: $\alpha(id_0, s) = s$

- compatibility: $\alpha(f \star g, s) = \alpha(f, \alpha(g, s))$


** Preorder, partial and linear order (Category)

*** Preorder as a category

A *preorder* is a category $\mathcal{C}(O, M, \bullet)$, where there is at most one
morphism between objects. It has the following properties:

- *reflexivity*: from identity morphisms

- *transitivity*: from composition of morphisms

*** Partial order as a category

A *partial order* (*poset*) is a preorder where there cannot be loops except for
identity arrows.

- *reflexivity*: from identity morphisms

- *transitivity*: from composition of morphisms

- *antisimmetry*: $x \rightarrow y \rightarrow x \Rightarrow x = y$

*** Linear order as a category

A Linear order is a partial order where:

\[x \rightarrow y \in M \Rightarrow y \rightarrow x \notin M\]

*** Meet

A *meet*

- is the unique *product* of two objects in a poset

- it is regarded as the *minimum* of two objects

- in boolean algebra, it can be seen as the *and* operation

*** Join

A *join*

- is the unique *coproduct* of two objects in a poset

- it is regarded as the maximum of two objects

- in boolean algebra, it can be seen as the *or* operation

*** Lattice as a category

[[https://ncatlab.org/nlab/show/lattice][A lattice]] is a poset where *all objects* have a *meet* and a *join*

** Special categories

*** Categorical nomenclature (*small* and *large* cats)

    - A *class* is a collection of sets that share a property.

    - Large category $C$: Either $ob(C)$ or both $ob(C)$ and $hom(C)$ are proper
      classes (i.e., a class that is not a set).

    - Locally small category $C$: $hom(C)$ is a set (*Set* is just an example)

    - Small category $C$: $ob(C)$ and $hom(C)$ are sets

*** Groupoid

 A (small) *groupoid* is a (small) category in which all morphisms are
 *isomorphisms*. I.e., composition has a *two sided inverse*.

*** Big category

 A category of categories ($CAT$) that:

 - has functors as morphisms
 - excludes itself.

*** Product category

Given two categories $C$ and $D$, a product category $C \times D$ is such that

- Objects are all possible pairs of original objects

- Morphisms are all the corresponding morphisms

*** Cartesian category

It is a category where a product is defined for all objects.
This product is a bifunctor $C \times C \rightarrow C$.

*** Cartesian closed category
It is a cartesian category that has exponentials and a terminal object.

*** BiCartesian closed category
It is a cartesian category that has exponentials and a terminal object and coproducts.

** Set category
*** Monomorphisms (Sets)
- $f$ is a monomorphism if $$\neg\exists (g_1, g_2) ~~ g_1 \neq g_2 \wedge f \circ g_1 = f \circ g_2$$

- Injective functions among sets can be classified as /monomorphisms/;

- *Assume* three sets $A,B$ and $C$ and $f: A \rightarrow B$, and $g_1, g_2 : C \rightarrow A$.
  If $f$ is non-injective, then the pre-composition with g_1 and g_2 (where g_1 and g_2
  differ only because they map the same element $z \in C$ into two different $a_1,
  a_2$ for which $f(a_1) = f(a_2)$) will be the same: $$f \circ g_1 = f \circ g_2$$ even if those are different.

*** Epimorphisms (Sets)

- $f$ is an epimorphism if $$\neg\exists (g_1, g_2) ~~ g_1 \neq g_2 \wedge g_1 \circ f = g_2
  \circ f$$.

- Surjective functions among sets can be classified as /epimorphisms/;

- *Assume* three sets $A,B$ and $C$ and $f: A \rightarrow B$, and $g_1, g_2: B \rightarrow C$.
  If $f$ is not surjective, there are elements in $B$ which will not participate
  to $g \circ f$ (/terra incognita/). There will be thus $g_1$ and $g_2$ that differ only in
  terms of those excluded terms while their composition is the same.

*** Terminal object (Sets)

There is a set 1 for which, for any set $X$, there is a unique function $X \rightarrow 1$.
This is called the *terminal object*.

*** Unit of categorical product (Sets)

The unit of a categorical product is the terminal object, $X \times 1 \simeq X$

*** Sets sharing an element (Sets)

If:

- there is a monomorphism $m: B \rightarrow X$

- and there is $k: 1 \rightarrow B$ such that $x: 1 \rightarrow X$ factors through $m$, i.e.,  $x = m \circ k$

then $x \in B$

*** Subobject (Sets)

Any object $B$ for which there exists a monomorphism $B \rightarrow X$ is a subset/subobject of $X$.

*** Equalizer (Sets)

Given two functions ($g_1, g_2: X \rightarrow Y$), an equaliser is an *object* and
 *monomorphism* *pair* $(E,m: E \rightarrow X)$ for which there hold the following properties:

1. *Equivalence*: $g_1 \circ m = g_2 \circ m$
2. *Limit*: There exists a unique morphism $O \rightarrow E$ for any other object pair
   $(O,m_o: O \rightarrow X)$ for which the above equivalence.

$E$ should be understood as the subset of elements of $X$ for which $g_1(x) = g_2(x)$, i.e., the solutions of the equation.

*** Function objects (Sets)
    - We can use a *universal construction* for a function object $f$ which represents the
      set of functions from object $a$ to $b$; we call this object $b^a$.
    - Ideally, $f$ is such that there exists a morphism $g: f \times a
      \rightarrow b$ and for all other morphisms $g': (f' \times a) \rightarrow b$
      there is a unique morphism $(h \times Id): (f' \times a) \rightarrow (f
      \times a)$ such that $g' = g \circ (h \times Id)$.

*** Currying
    - Assume $b^a$ the function object from $a$ to $b$
    - If $f$ is a function it can be seen as a subobject (member) of $b^a$. As
      such, by universal construction of exponentials, there is an one to one
      correspondence called *currying*: $$f \rightarrow (b^a) \sim (f \times a) \rightarrow b$$

** Kleisly category
*** Kleisly category ($C_T$) definition
    - $C_T$ can be constructed from a category $C$ with an endofunctor $T$ (such
      as *Set*) where any morphism $A \rightarrow_T B$ is built by picking a
      morphism $A \rightarrow T B$ such that:
      - Identity for any $A$ is built by picking a morphism $\eta_A: A
        \rightarrow T A$
      - Composition $h_T = f_T \circ g_T : A \rightarrow_T C$ is built by picking an $h: A
        \rightarrow T C$ such that $$ h = \mu \circ T f \circ g$$ where
        $\mu$ is a multiplication functor ($\mu: T^2 C \rightarrow T C$).


** Monoidal category
*** Monoidal category definition
   - A category $C$ is *monoidal* if all pairs of objects have a product
     (co-product) and a terminal (initial) object.

   - Both product and coproduct in a monoidal category are individuated by the
     same symbol, i.e., *tensor product* ($\otimes$)

* Functors
** Introduction
*** Functor definition

A functor \[ F : \mathcal{C} \rightarrow \mathcal{C'} \] is a pair $(F_o, F_m)$ where

- $F_o$ maps objects across categories $\mathcal{C}$ and $\mathcal{C'}$, while

- $F_m$ maps morphisms with laws $F(id_o) = id_F(o)$ and $F(h \bullet g) = F(h) \bullet F(g)$

- It preserves composition and identity

*** Full functor

A *full functor* $T: C \rightarrow D$ is an *epimorphism* between morphisms in $C$ and $D$.

*** Faithful functor

A faithful functor $T: C \rightarrow D$ is a *monomorphism* between morphisms in $C$ and $D$.


*** Identity functor
    $Id: C \rightarrow C$ is a functor that maps an object to itself and a
    function to itself.

*** Constant $\Delta_c$ functor
    A constant functor $\Delta_c: B \rightarrow C$ is a functor that maps every
    object in $B$ into a single object $c \in C$.

*** Bifunctors

- A bifunctor over $C$ and $D$ is a functor over pairs of objects and morphisms,
  i.e., $C \times D \rightarrow E$

- Products and co-products are special bifunctors $C \times C \rightarrow C$

*** Contravariant functors

    A contravariant functor is a functor $C^{op} \rightarrow D$.

*** Profunctors

    A pro-functor is a functor $C^{op} \times C \rightarrow C$. It can be used
    to describe the functoriality of the 'arrow' (exponential) object construction.

*** Combination of functors

    - $T(X) = X = Id$ is a functor

    - $T(X) = A = \Delta_A$ is a functor

    - If $F_1(X)$ and $F_2(X)$ are functors then $T(X) = F_1(X) + F_2(X)$ is a
      functor
    - If $F_1(X)$ and $F_2(X)$ are functors then $T(X) = F_1(X) * F_2(X)$ is a functor

    - If $F_1(X)$ is a functor then $T(X) = F_1(X)^A$ is a functor


    Thus any polynomial expression in an object $X$ can be made into a functor.

*** Curry-Howard-Lambek isomorphism


    | *Logic*          | $\top$   | $\bot$  | $a \wedge b$ | $a \vee b$ | $a \Rightarrow b$ |
    | *Types*          | ()       | Void    | (a,b)        | Either a b | $a \rightarrow b$ |
    | *C. C. Category* | terminal | initial | $a \times b$ | $a + b$    | $b^a$             |

    - Proving a logic predicate means constructing an element of a specific type

    - A cartesian closed category is a model for logic and category theory


* Limits
** Basic limits theory
*** Selecting objects

In any category, I can pick objects by expressing a pattern. This defined
through another another category and a functor.

Picking two objects from $C$ means a functor $\textbf{2} \rightarrow C$.

*** Products as limit
* Functor algebra
** Functor algebra introduction
*** Definition of algebras and co-algebras
    - An algebraic operation in domain $X$ is a morphism from tuple objects to $X$
      e.g.: $$ X \times A
      \rightarrow X$$ or $$ A \rightarrow X $$

    - A co-algebraic operation in domain $X$ is a morphism from $X$ into a tuple
      object, possibly containing $X$: $$ X \rightarrow A \times
      X $$

*** Functoriality of products, coproducts, exponential and powersets

    - The product operation in a category $C$ is a bi-functor $(-) \times (-): C
      \times C \rightarrow C$ (it maps both *pairs of objects* to a *product object*
      and *pairs of functions* to a *product function*).

    - Fixed an object $A$ there is a functor $(-)^A: C \rightarrow C$ that maps $X$
      into $X^A$ (the exponential object).

    - The identity map is (endo-)functorial as well as the endomap that maps $X$
      into a fixed object.

*** Functoriality when combining of product and coproducts

    - If we can build functors for products and coproducts, we can build functors
      also for their combination;

    - For example: $T(X) = X + (C \times X)$
      maps X to an object $X + (C \times X)$ but also morphisms $f: X \rightarrow X'$:

      $$T(f) = f + (id_C \times f): X+(C\times X) \rightarrow X'+(C \times X')$$

*** Functoriality for initial and final object isomorphisms

    - $X \rightarrow 1$ is the functor that maps $X$ into the singleton set (final object)

    - $X \rightarrow 0$ is the functor that maps $X$ into the emtpy set (initial object)

*** Equivalence between functors

    - There are isomorphisms that make some functors equivalent, e.g. $X \times
      Y = Y \times X$ or $(X \times (Y + Z)) = (X \times Y) + (X \times Z)$.

    - They follow the same rules of addition and multiplication of numbers
*** Functor algebra

    Given a polynomial (endo-)functor $T$ that maps $X \in C$ to $T(X) \in
    C$, a functor algebra for $T$ is a pair $(U,a)$:

    - an object $U \in C$ (*carrier*)
    - a morphism $a: T(U) \rightarrow U$ (*algebra structure*)

    $a$ must be defined by a cotuple of several functions whose signature is
    specified by $T$. For example, $$T(X) = 1 + X + (X \times X)$$ defines $$e:
    1 \rightarrow U, i: X \rightarrow X, m: (X \times X) \rightarrow X$$ which
    might encode the signature of group operations.

*** Functor algebra example - natural numbers

    $0$ and $S$ maps over natural numbers can be seen as a functor algebra
    $([0,S],\mathbb{N})$ of the functor $T(X) = 1 + X$.

*** Homomorphisms of algebras

    Given two T-functor algebras $(U, a: T(-) \rightarrow -)$ and $(V, b: T(-) \rightarrow -)$,
    a homomorphism of algebras from $(U,a)$ to $(V,b)$ is a function $f: U \rightarrow V$ which commutes
    with the operations $$ f \circ a = b \circ T(f)$$

*** Initial algebras
    - Fixed a functor $T$, functor algebras $(U, a: T(U) \rightarrow U)$ can be
      seen as categorical objects with algebra homomorphisms as morphism.

    - In this category, an *initial algebra* is an algebra for which there exist
      one and only one morphism from it to all the other algebras.

*** Lambek's lemma
    if $a: T(U) \rightarrow U$ is an initial algebra then there is an
    inverse $a^{-1}: U \rightarrow T(U)$ such that $T(U) \simeq U$.

*** An initial algebra defines homomorphisms by induction (integers)

    - Let's indicate with $(N, [0,S]: 1 + N \rightarrow N$) the *initial* algebra of
      natural numbers.

    - An object $Q$ equipped with a functor algebra $$(Q, [q_0,q_S]:
      1+Q\rightarrow Q)$$ defines, by induction, one and only one algebra
      morphism $f: N \rightarrow Q$.

      - $f \circ 0 = q_0$
      - $f \circ S = q_S \circ f$

      i.e, $$f = n \mapsto q_S^n(q_0)$$

*** An initial algebra defines homomorphisms by induction (lists)

    * Let's indicate with $(A^*, [e,c]: 1 + A \times A^* \rightarrow A^*$) the
      *initial* algebra of lists of $A$.

    * An algebra $$(Q^*, [q_e,q_c]:
      1+A \times Q^* \rightarrow Q^*)$$ defines, by induction, one and only one algebra
      morphism $f: A^* \rightarrow Q^*$.

      - $f \circ e = q_e$
      - $f \circ c = q_c \circ (id \times f)$

    * For example, an algebra $$(\mathbb{N}, [0, S \circ \pi]: 1+A \times
      \mathbb{N} \rightarrow \mathbb{N})$$ defines implicitly the length of a list

*** Proofs by induction with initial algebras

    - Consider that, given an initial algebra $(U, a: T(U) \rightarrow U)$, any
      homomorphism $f: U \rightarrow V$ to a second algebra $(V, b)$ is the
      same.

    - So, for example, verifying a property of $f: U \rightarrow
      U$ can be written by demonstrating $prop_1 \circ f$ and
      $prop_2$ are homomorphisms from the same initial into algebra into the
      same target algebra.
