
#+TITLE: Algebra
#+AUTHOR: Vittorio Zaccaria
#+INCLUDE: ./beamer_modern.org
#+LEVEL: 3

#+OPTIONS:   H:3 num:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t ':t


* Algebraic structures

** Other structures 
*** Magma
    A magma is set $M$ equipped with a single binary operation,
    $(*): M \times M \rightarrow M$ that satisfies:

   - *closure*: every element can be described as a fold of other elements of the set.

** Semigroups
*** Semigroup binary operation properties
   
   A [[https://en.wikipedia.org/wiki/Semigroup][semigroup]] is a set equipped with one binary operation (*) that satisfies:

   - *closure*: every element can be described as a fold of other elements of the set.
   - *associativity*: $(a * b) * c = a * (b * c)$.

** Monoids
*** Monoid
   
   A monoid $(M,*)$ is a *semigroup* with a unit element ($1 \in M$) where the $*$ 
   operation satisfies:
   
   - *identity*: $a * 1 = a, \forall a \in M$.

*** Categorical view of a monoid 
    A *monoid* can be seen as a category with a single object. 

    Monoid elements are represented by the categorical morphisms (associativity
    is preserved).

*** Generator set (Monoid)
    A subset $S$ of $M$ is said to be a generator if all elements $y \in M$ 
    can be obtained by some kind of *fold* of the elements $x \in S$.

    \[
      \forall y \in M, \exists a_1, \ldots, a_n \in S \textrm{~~s.t.~~} y = a_1 * \cdots * a_n
    \]

*** *Free* generator set (Monoid)
    A subset $S$ of $M$ is said to be a free generator if all elements $y \in M$ 
    can be obtained by a *unique fold* of the elements $x \in S$:

    \[
      \forall y \in M, \exists a_1, \ldots, a_n \in S \textrm{~~s.t.~~} y = a_1 * \cdots * a_n
    \]

    Not all generator sets are free. For example, $\{1\}$ is a generator for
    $\mathbb{Z}_n$ but it is not free, in the sense that each element of
    $\mathbb{Z}_n$ can be defined by multiple sequences of 1.

*** Free monoid
    A monoid with a free generator set is called a *free monoid*.

    Example: $(\mathbb{N}, +)$ is the *free monoid generated by 1*.

*** Abelian monoid
    A monoid $(M,*)$ where $\forall a,b \in M, a * b = b * a$

*** Commutative monoid
    It is an Abelian monoid

*** Monoid homomorphisms 
    Given two monoids $(X,\star)$ and $(Y, *)$, a homomorphism $f: (X,\star)
    \rightarrow (Y,*)$ is a function $f: X \rightarrow Y$ such that:
    
    \[
      f(1_X) = 1_Y \textrm{~~and~~} f(m \star n) = f(m) * f(n)
    \]

** Groups
*** Group
   
   A [[https://en.wikipedia.org/wiki/Group_(mathematics)][group]] is a monoid where for all elements $a$, the (*) operation satisfies:

   - *invertibility*: $a * a^{-1} = 1$.
   - *associativity*: $a * (b * c) = (a * b) * c$ 

   In a group, every element has its own inverse.

*** Subgroup  
   $H$ is a [[https://en.wikipedia.org/wiki/Subgroup][subgroup]] of $G$ if:

   - it is a subset of $G$ 
   - it forms a group under the operation (*).

   The *trivial subgroup* of any group is the subgroup ${e}$ consisting of just the identity element.

*** Coset 
    Given a subgroup $H$ and some $a$ in $G$, we define the *left coset* of $H$ as
    $aH = \{ah : h \in H\}$. We have some properties holding:

    - each $a$ generates a subset of $G$ and, considering all the elements $a$
      of $G$, the corresponding set of cosets of $H$ is a partition of $G$.

    - all cosets of $H$ have the same amount of elements (which is the same number of elements of $H$). 

    - because the family of cosets is a partition, the size of $G$ is a multiple of $H$ and its cosets.
    
** Semirings
*** Semiring (Rig)
    A [[https://en.wikipedia.org/wiki/Semiring][semiring]] $R$ consists of a set equipped with two binary operations that generalize
    the arithmetic operations of addition and multiplication, i.e.:

    - $(R, +)$ is a commutative monoid with identity = 0 (note, *not a group*, it
      should not have an inverse).
    - $(R, *)$ is a monoid with identity = 1
    - multiplication distributes over addition
    - multiplication by 0 gives 0 (annihilates).
   
** Rings 
*** Ring

    A [[https://en.wikipedia.org/wiki/Ring_(mathematics)][ring]] $R$ consists of a set equipped with two binary operations that generalize
    the arithmetic operations of:
    
    - $(R, +)$ is a commutative *group* with identity=0 (note that it should have
      an inverse).
    - $(R, *)$ is a monoid with identity = 1
    - multiplication distributes over addition
    - multiplication by 0 gives 0 (annihilates).

*** Ideals 
    An *ideal* $I$ is a special subset of a ring $R$ that respects the following properties:

    - *closure*: summing two elements of $I$ gives another element of $I$.
    - *absorption*: multiplying an element of $I$ by any other element in $R$
      gives an element of $I$.

    Example: the even numbers are an ideal of the natural numbers

** Fields

*** Field

    A [[https://en.wikipedia.org/wiki/Field_(mathematics)][field]] a set with two operations:

    - $(F, +)$ is a commutative group 
    - $(F, *)$ is a commutative group 

*** Field characteristic 

    Given a multiplication operator \[ \cdot: \mathbb{N}^+ \times F \rightarrow
    F \] that corresponds to an element of $F$ multiplied by itself $n$ times,
    we say that if there is $n$ such that $n \cdot 1_{*}$ is 0, then this field
    has characteristic $n$.

    IF there is $n \neq 0$, then $n$ is prime, else it is 0.

*** Prime field of F
    It is a subfield of F. It is composed by all the elements of $F$ that are
    multiple of the unity. If the field has characteristic $p$, then its prime
    field is isomorphic to $F_p$.

*** Finite field F
    It has finitiely many elements. For example, for any prime number $p$ there
    is a finite field $F_p$ where the arithmetic operations are understood as
    modular.
* Algebras  

** Vector spaces 

*** Vector space
    
    Set of elements (called *vectors*) which can be added together and multiplied
    by scalars (i.e., elements of a field $K$). So, both addition and scalar
    multiplication should be defined. Subtraction and division come from scalars.

*** Simple vectors

    They are ordered sequences of elements that belong to a field ([[https://en.wikipedia.org/wiki/Scalar_(mathematics)][scalars)]].
    Classical results of geometry apply.

*** Normed vector spaces
    
    A *normed* vector space $V$ is endowed with a map $V \rightarrow R$. 

*** Inner product spaces 
    
    An *inner product* space $V$ is endowed with an operation $V \times V \rightarrow R$.

*** Algebra over a field

    It is a vector space equipped with a bi-linear operator acting as *multiplication* between vectors.

    Examples: 
    
    - $R^3$ with cross-product $\times$

*** Tensor algebra 
   
    Multiplication is just a concatenation of symbols. [[https://en.wikipedia.org/wiki/Algebra_over_a_field][(wikipedia)]]

** Modules 

*** Module

    Generalization of vector space. Elements can still be added together and can
    be "multiplied" with elements of a ring (instead of a field). 
  
