
#+TITLE: Algebra
#+AUTHOR: Vittorio Zaccaria
#+LEVEL: 3



* Simple algebraic structures

** Other structures 
*** Magma
    A magma is set $M$ equipped with a single binary operation,
    $(*): M \times M \rightarrow M$ that satisfies:

   - *closure*: $a \in M, b \in M \rightarrow a * b \in M$ 

** Monoids
*** Monoid
   
   A monoid $(M,*)$ is a *semigroup* with a unit element ($1 \in M$) where the $*$ 
   operation satisfies:
   
   - *identity*: $a * 1 = a, \forall a \in M$.

*** Generator set (Monoid)
    A subset $S$ of $M$ is said to be a generator if all elements $y \in M$ 
    can be obtained by some kind of *fold* of the elements $x \in S$.

    \[
      \forall y \in M, \exists a_1, \ldots, a_n \in S \textrm{~~s.t.~~} y = a_1 * \cdots * a_n
    \]

*** Free generator set (Monoid)
    A subset $S$ of $M$ is said to be a free generator if all elements $y \in M$ 
    can be obtained by a *unique fold* of the elements $x \in S$:

    \[
      \forall y \in M, \exists a_1, \ldots, a_n \in S \textrm{~~s.t.~~} y = a_1 * \cdots * a_n
    \]

    Not all generator sets are free. For example, $\{1\}$ is a generator for
    $\mathbb{Z}_n$ but it is not free, in the sense that each element of
    $\mathbb{Z}_n$ can be defined by multiple sequences of 1.

*** Free monoid
    A free monoid is a monoid with a free generator.

    Example: $(\mathbb{N}, +)$ is the *free monoid generated by 1*.

*** Abelian monoid
    A monoid $(M,*)$ where $\forall a,b \in M, a * b = b * a$

*** Monoid homomorphisms 
    Given two monoids $(X,\star)$ and $(Y, *)$, a homomorphism $f: (X,\star)
    \rightarrow (Y,*)$ is a function $f: X \rightarrow Y$ such that:
    
    \[
      f(1_X) = 1_Y \textrm{~~and~~} f(m \star n) = f(m) * f(n)
    \]


** Groups
*** Group
   
   A [[https://en.wikipedia.org/wiki/Group_(mathematics)][group]] $G$ is a monoid where for all elements $a$, the (*) operation satisfies:

   - *closure*: $a \in G, b \in G \rightarrow a * b \in G$
   - *identity element*: $a * 1_G = 1_G * a = a$
   - *invertibility*: $a * a^{-1} = 1$.
   - *associativity*: $a * (b * c) = (a * b) * c$ 

   In a group, every element has its own inverse.

*** Subgroup  
   $H$ is a [[https://en.wikipedia.org/wiki/Subgroup][subgroup]] of $G$ if:

   - it is a subset of $G$ 
   - it forms a group under the operation (*).

   The *trivial subgroup* of any group is the subgroup ${e}$ consisting of just the identity element.

*** Coset 
    Given a subgroup $H$ and some $a$ in $G$, we define the *left coset* of $H$ as
    $aH = \{ah : h \in H\}$. 

*** What is the set of cosets of a subgroup of $G$?

    It is a partition of $G$.

*** How many elements has each coset of $H$ (a subgroup of $G$)?
    
    All cosets of $H$ have *the same amount* of elements of $H$ 

*** What is the size of a group $G$ with respect to the size of the cosets of its subgroup $H$?

    The size of $G$ is a multiple of the size of $H$ (and in turn, also of the size of its cosets).
    
*** Semigroup 
   
    A [[https://en.wikipedia.org/wiki/Semigroup][semigroup]] $S$ is a "group without inverse".

   - *closure*: $a \in G, b \in G \rightarrow a * b \in G$
   - *identity element*: $a * 1_G = 1_G * a = a$
   - *associativity*: $(a * b) * c = a * (b * c),~~a,b,c \in G$.
