#+TITLE: Algebra
#+AUTHOR: Vittorio Zaccaria
#+LEVEL: 3
#+OPTIONS: H:3

* Algebraic structures with one operator
** Other structures
*** Magma
    A magma is set $M$ equipped with a single binary operation,
    $(*): M \times M \rightarrow M$ that satisfies:

   - *closure*: $a \in M, b \in M \rightarrow a * b \in M$

** Monoids
*** Monoid

   A monoid $(M,*)$ is a *semigroup* with a unit element ($1 \in M$) where the $*$
   operation satisfies:

   - *identity*: $m * 1 = m, \forall m \in M$.

*** Generator set (Monoid)
    A subset $S$ of $M$ is said to be a generator if all elements $m \in M$
    can be obtained by some kind of *fold* of the elements $s \in S$.

    \[
      \forall m \in M, \exists s_1, \ldots, s_n \in S \textrm{~~s.t.~~} m = s_1 * \cdots * s_n
    \]

*** Free generator set (Monoid)

    A subset $S$ of $M$ is said to be a generator if all elements $m \in M$
    can be obtained by a *unique fold* of the elements $s \in S$.

    \[
      \forall m \in M, \exists s_1, \ldots, s_n \in S \textrm{~~s.t.~~} m = s_1 * \cdots * s_n
    \]

    Not all generator sets are free. For example, $\{1\}$ is a generator for
    $\mathbb{Z}_n$ but it is not free, in the sense that each element of
    $\mathbb{Z}_n$ can be defined by multiple sequences of 1.

*** Free monoid

    - A free monoid is a monoid *with a free generator*.

    - Example: $(\mathbb{N}, +)$ is the *free monoid generated by 1*.

*** Abelian monoid
    A monoid $(M,*)$ where $$\forall m_1,m_2 \in M, m_1 * m_2 = m_2 * m_1$$

*** Monoid homomorphisms
    Given two monoids $(X,\star)$ and $(Y, *)$, a homomorphism $$f: (X,\star)
    \rightarrow (Y,*)$$ is a function $f: X \rightarrow Y$ such that:

    \[
      f(1_X) = 1_Y \textrm{~~and~~} f(m \star n) = f(m) * f(n)
    \]

** Groups
*** Group

   A [[https://en.wikipedia.org/wiki/Group_(mathematics)][group]] $G$ is a monoid where for all elements $a$, the (*) operation satisfies:

   - *closure*: $a \in G, b \in G \rightarrow a * b \in G$
   - *identity element*: $a * 1_G = 1_G * a = a$
   - *invertibility*: $a * a^{-1} = 1$.
   - *associativity*: $a * (b * c) = (a * b) * c$

   In a group, every element has its own inverse.

*** Subgroup
   $H$ is a [[https://en.wikipedia.org/wiki/Subgroup][subgroup]] of $G$ if:

   - $H \subseteq G$
   - It is closed under (*).

   The *trivial subgroup* of any group is the subgroup ${e}$ consisting of just the identity element.

*** Normal subgroup
    $H$ is a normal subgroup of $G$ iff $$\forall h \in H \wedge g \in G, ghg^{-1} \in H$$

*** Kernel of a group homomorphism
    The *kernel* $\textrm{ker}(f)$ of a group homomorphism $f: (G,\star)
    \rightarrow (H,*)$ is a set $K$ such that

    - $K \subseteq G$
    - $\forall k \in K, f(k) = 1_{*}$

*** Range of a group homomorphism
    The *range* $\textrm{range}(f)$ of a homomorphism  $f: (G,\star)
    \rightarrow (H,*)$ is a set $R$ such that

    - $R \subseteq H$
    - $\forall r \in R, \exists g \in G \textrm{~s.t.~} r = f(g)$

*** Coset
    Given a subgroup $(H, \star) \subseteq (G, \star)$, we define the *left coset* of $H$ as
    $$H_g = \{g \star h : h \in H\}$$

*** What is the set of cosets of a normal subgroup $H$ of $G$?

    It is a partition of $(G, \star)$ and it is a group where the operation is defined as
    $$Hg_1 \star Hg_2 = H(g_1 \star g_2)$$


*** Subgroup of an abelian group
    Every subgroup of an abelian group is normal.

*** Coset multiplication

    Coset multiplication operation: $$Hg_1 * Hg_2 = H(g_1 \star g_2),~~g_1,g_2 \in G$$

*** Factor/quotient group

    - If $H$ is a normal subgroup of $G$, coset multiplication is a group
      operation of a particular group: the *factor (or quotient) group*.

    - The factor group $G/H$ is a group where elements are the
      cosets of $G$ by $H$ and group operation is cosets multiplication.

*** Construct a quotient group $Z/6Z$.


    - $(G, +) = Z$
    - $(H, +) \subseteq (G,+) = 6Z$ is the subgroup of all multiples of 6 in $Z$
    - *elements* of the quotient group are all the unique cosets $$H_g = \{ 6Z + g, g \in Z \}$$
      (their elements are infinite, but there are only 6 of them, $H_1=H_7=\ldots$).
    - the *operation* among cosets $$Hg_1 + Hg_2 = H_{g_1 + g_2}$$  respects
      the quotient group properties.

    This quotient group is also called *the cyclic group $Z_6$*.

*** Homomorphisms of a group into a quotient group
    Given a quotient group $G/H$, there is a homomorphism $G \rightarrow G/H$.

*** How many elements has each coset of $H$ (a subgroup of $G$)?

    All cosets of $H$ have *the same amount* of elements of $H$

*** What is the size of a group $G$ with respect to the size of the cosets of its subgroup $H$?

    The size of $G$ is a multiple of the size of $H$ (and in turn, also of the size of its cosets).

*** Semigroup

    A [[https://en.wikipedia.org/wiki/Semigroup][semigroup]] $S$ is a "group without inverse".

   - *closure*: $a \in G, b \in G \rightarrow a * b \in G$
   - *identity element*: $a * 1_G = 1_G * a = a$
   - *associativity*: $(a * b) * c = a * (b * c),~~a,b,c \in G$.



*** Group identity and inverse properties

    Both the identity and the inverse of every element are *unique*.

*** Endomorphism ring of an abelian group

    Given a group $(A,+)$, we can define a set F of group homomorphisms:
    \[
      F = End(A) = \{ f: f(a + b) = f(a) + f(b), \forall a,b \in A \}
    \]

    $End(A,++,\circ, \textrm{const~} 0, \textrm{const~} 1)$ is a *ring* (of functions) where

    - $(f ++ g)(x) = f(x) + g(x)$
    - $(f \circ g)(x) = f(g(x))$

*** Order of a group element
    In a group, the least integer $n$ such that $a^n=1_{*}$, then that element
    has order $n$.

*** Cyclic group
    If $G$ has an element $a$ and all its elements are powers of $a$, then $G$ is cyclic:
    $$G = \{ a^n : n \in Z \}$$

    $a$ is called generator and the group order is the order of $a$.

*** Symmetric group
    The symmetric group $S_n$ is the group of all permutations (symmetries) of $\{1, . . . , n\}$

*** Group action

     - A group action $\phi$ of group $G$ on a set $X$ is a function
       $$*: G \times X \rightarrow X$$ satisfying the following properties:

       - identity: $e * x = x$
       - compatibility: $(gh) * x = g * (h * x)$

     - An action $g * x$ is the same as a group homomorphism $G \rightarrow \textrm{Aut}(X)$

*** Linear group representation

    - A *linear group representation* of $G$ is a group homomorphism
      $$\rho : G \rightarrow GL(V)$$

    - It represents the elements of $G$ as *symmetries of the vector space* $V$.

*** Properties of a linear group representation

    - $\rho_g \rho_h = \rho_{gh}$
    - $\rho_1 = Id$
    - $(\rho_g)^{-1} = \rho_{g^{-1}}$
    - $\rho_g(xv + yw) = x\rho_gv + y\rho_gw$


*** Permutation representation
     - The *permutation representation* is associated with a symmetric group $G =
       S_n$ and acts on a $V_k = k^n$.

     - A permutation representation $\rho: S_n \rightarrow GL(k^n)$
       is such that $$\rho_s(x_1 \ldots x_n) = (x_{s(1)} \ldots x_{s(n)})$$.

*** Sign representation
    - If $\rho(S_n)$ is a representation, then $\texrm{det}\rho(S_n)$ is a sign
      representation as it is either 1 or -1.

*** Left regular representation

    - Given a group $G$ and a field $K$ we can define a group algebra $K(G)$
      where vectors are of the form:

      $$f = \sum_{g\in G}a_{g,f} e_g$$

    - A left regular representation $\rho: G \rightarrow GL(K(G))$
      is such that $$\rho(s)f = \rho(s)\sum_{g\in G}a_{g,f} e_g = \sum_{g\in G}a_{g,f} e_{s*g}$$

*** Faithful representation

    A *faithful* representation $\rho(g)$ is an *injective* map, i.e., $$\textrm{Ker}(\rho)={1_G}$$

*** Trivial representation

    - A representation $\rho: G \rightarrow GL(E_k)$ is trivial if all $g \in G$
      map to an identity matrix.

*** Intertwining operator

  - An intertwining operator is a functor $\Phi_{ij}: E_i \rightarrow E_j$ that
    preserves representations: $$\Phi_{ij}(\rho_i(g)v)=\rho_j(g)\Phi_{ij}(v)$$.

  - As such, it introduces a homomorphism between representations $$\rho_2
    = \Phi_{12} \rho_1$$ which comply with composition.

  - We can thus say that any group $G$ defines a *category of representations* and
    we can speak of its morphisms (intertwiner) as $Hom_G(\rho_1, \rho_2)$.

*** Subrepresentations
   - Given a subspace $F \subseteq E$, if $$\forall f \in F, ~~\rho(G)(f) \in
     F$$ then $(\rho, F)$ is a *subrepresentation* of $(\rho, E)$.

*** Trivial subrepresentation

   - the /space of invariants/ $E^G \subseteq E$ such that $\rho(g)e = e$ corresponds to
     a *subrepresentation* $(\rho, E^G)$ that is trivial.

   - in fact, $E^G$ is isomorphic to $Hom_G(1,E)$, i.e., the space of constant functions
     over $E$.

*** One dimensional representation

  - A one-dimensional $k$ representation is built above a homomorphism $\chi: G
    \rightarrow k^{\times}$ and corresponds to a representation $\rho_k(g) =
    \chi(g)Id_{V}$ ($\chi(\cdot)$ is in fact a scalar).

  - Can we determine $\lambda$? If we know an intertwiner $\phi: \rho_k
    \rightarrow \rho$ then $\lambda$ should satisfy, for all $g$:

\[
\begin{array}{rcl}
(\phi \lambda Id)v & = & (\rho(g) \phi)v \\
(\lambda \phi)v & = & (\rho(g) \phi)v \\
\lambda u & = & \rho(g) u \\
\end{array}\]

  - $\lambda$ is thus the eigenvalue of all representations $\rho(g)$


* Algebraic structures with two operators
** Semirings
*** Semiring (Rig)
    A [[https://en.wikipedia.org/wiki/Semiring][semiring]] $R$ consists of a set $R$ such that:

    - $(R, +)$ is a commutative monoid with identity = 0 (note, *not a group*, it
      should not have an inverse).
    - $(R, *)$ is a monoid with identity = 1
    - multiplication distributes over addition
    - multiplication by 0 gives 0 (annihilates).

** Rings
*** Ring

    A [[https://en.wikipedia.org/wiki/Ring_(mathematics)][ring]] $R$ consists of a set $R$ such that:

    - $(R, +)$ is a *commutative* *group* with identity=0 (note that it should have
      an inverse).
    - $(R, *)$ is a monoid with identity = 1 (Semigroup)
    - multiplication distributes over addition
    - multiplication by 0 gives 0 (annihilates).

*** Ideals
    An *ideal* $I$ is a special subset of a ring $R$ that respects the following properties:

    - *closure*: $+: I \times I \rightarrow I$ is total.
    - *absorption*: $*:I \times R \rightarrow I$ is total.

    Example: the even numbers are an ideal of the natural numbers

*** Ring homomorphism

    If $R$ and $S$ are rings, a ring homomorphism $f: R \rightarrow S$ is a
    total function such that:

    - $f(a + b) = f(a) + f(b)$
    - $f(a * b) = f(a) * f(b)$
    - $f(1_R) = 1_S$


** Fields

*** Field

    A [[https://en.wikipedia.org/wiki/Field_(mathematics)][field]] a set with two operations:

    - $(F, +)$ is a commutative group
    - $(F, *)$ is a commutative group

*** Field characteristic

    A field has characteristic $n$ if $1_{*}$ summed with it self $n$ times gives
    $0_{+}$.

    The following relation is found to hold: $$ n > 0 \leftrightarrow
    \textrm{prime}(n)$$

*** Prime field F
    A finite field of order $p$ where $p$ is prime.

*** Finite field $F_p$
    It has $p$ elements. If $p$ is prime then $F_p$ is a prime field and
    operations are understood as modular.



* Algebras of vector spaces and modules
** Vector spaces

*** Vector space

    A pair $(V,K)$ where

    - $(K,(+,0),(\cdot,1))$ is a field
    - $(V,+,e)$ is an abelian group under addition

    Moreover, the following operation should be total (scalar multiplication)
    \[
    *: K \times V \rightarrow V
    \]

*** Simple vectors

    They are ordered sequences of elements that belong to a field ([[https://en.wikipedia.org/wiki/Scalar_(mathematics)][scalars)]].
    Classical results of geometry apply.

*** Normed vector spaces

    A *normed* vector space $V$ is endowed with a map $V \rightarrow R$.

*** Inner product spaces

    An *inner product* space $V$ is endowed with an operation $V \times V \rightarrow R$.

*** Algebra

    - It is a module/vector space equipped with a bi-linear operator $$ \times: V \times V
      \rightarrow V$$ acting as *multiplication* between vectors.

    - The following axioms should hold:

      - Right distributivity: $(x + y) \times z = x \times z + y \times z$
      - Left distributivity: $x \times (y + z) = x \times y + x \times z$
      - Compatibility with scalars: $(ax) \times (by) = (ab) (x \times y)$.

*** Group Algebra

    Given a group $G$ and a field $K$, we can build an algebra $K[G]$ where

    - vectors are functions $f: G \rightarrow K$ for $K$ either a ring or
      field.
    - $(f_1 + f_2) = g \mapsto f_1(g) + f_2(g)$
    - $(\alpha f) = g \mapsto \alpha f(g)$
    - $(f_1 \times f_2) = g \mapsto \sum_{u \in G}f_1(u)f_2(u^{-1}g)$

    - Sometimes vectors $f$ are written as /linear combinations of the elements
      of $G$ with coefficients in K/, i.e., $$f = \sum_{g\in G}a_{g,f} e_g$$ where
      $e_g$ are basis in $K[G]$.


*** R-Module

    Generalization of vector space. A pair $(V,K)$ where

    - $(K,(+ ,0),(\cdot,1))$ is a *ring*
    - $(V,+,e)$ is an abelian group under addition

    Moreover, the following operation should be total (scalar multiplication)
    \[
    *: K \times V \rightarrow V
    \]
