
#+TITLE: Algebra
#+AUTHOR: Vittorio Zaccaria
#+INCLUDE: ./beamer_modern.org
#+LEVEL: 3

#+OPTIONS:   H:3 num:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t ':t


* Algebraic structures



** Semirings
*** Semiring (Rig)
    A [[https://en.wikipedia.org/wiki/Semiring][semiring]] $R$ consists of a set equipped with two binary operations that generalize
    the arithmetic operations of addition and multiplication, i.e.:

    - $(R, +)$ is a commutative monoid with identity = 0 (note, *not a group*, it
      should not have an inverse).
    - $(R, *)$ is a monoid with identity = 1
    - multiplication distributes over addition
    - multiplication by 0 gives 0 (annihilates).
   
** Rings 
*** Ring

    A [[https://en.wikipedia.org/wiki/Ring_(mathematics)][ring]] $R$ consists of a set equipped with two binary operations that generalize
    the arithmetic operations of:
    
    - $(R, +)$ is a commutative *group* with identity=0 (note that it should have
      an inverse).
    - $(R, *)$ is a monoid with identity = 1
    - multiplication distributes over addition
    - multiplication by 0 gives 0 (annihilates).

*** Ideals 
    An *ideal* $I$ is a special subset of a ring $R$ that respects the following properties:

    - *closure*: summing two elements of $I$ gives another element of $I$.
    - *absorption*: multiplying an element of $I$ by any other element in $R$
      gives an element of $I$.

    Example: the even numbers are an ideal of the natural numbers

** Fields

*** Field

    A [[https://en.wikipedia.org/wiki/Field_(mathematics)][field]] a set with two operations:

    - $(F, +)$ is a commutative group 
    - $(F, *)$ is a commutative group 

*** Field characteristic 

    Given a multiplication operator \[ \cdot: \mathbb{N}^+ \times F \rightarrow
    F \] that corresponds to an element of $F$ multiplied by itself $n$ times,
    we say that if there is $n$ such that $n \cdot 1_{*}$ is 0, then this field
    has characteristic $n$.

    IF there is $n \neq 0$, then $n$ is prime, else it is 0.

*** Prime field of F
    It is a subfield of F. It is composed by all the elements of $F$ that are
    multiple of the unity. If the field has characteristic $p$, then its prime
    field is isomorphic to $F_p$.

*** Finite field F
    It has finitiely many elements. For example, for any prime number $p$ there
    is a finite field $F_p$ where the arithmetic operations are understood as
    modular.
* Algebras  

** Vector spaces 

*** Vector space
    
    Set of elements (called *vectors*) which can be added together and multiplied
    by scalars (i.e., elements of a field $K$). So, both addition and scalar
    multiplication should be defined. Subtraction and division come from scalars.

*** Simple vectors

    They are ordered sequences of elements that belong to a field ([[https://en.wikipedia.org/wiki/Scalar_(mathematics)][scalars)]].
    Classical results of geometry apply.

*** Normed vector spaces
    
    A *normed* vector space $V$ is endowed with a map $V \rightarrow R$. 

*** Inner product spaces 
    
    An *inner product* space $V$ is endowed with an operation $V \times V \rightarrow R$.

*** Algebra over a field

    It is a vector space equipped with a bi-linear operator acting as *multiplication* between vectors.

    Examples: 
    
    - $R^3$ with cross-product $\times$

*** Tensor algebra 
   
    Multiplication is just a concatenation of symbols. [[https://en.wikipedia.org/wiki/Algebra_over_a_field][(wikipedia)]]

** Modules 

*** Module

    Generalization of vector space. Elements can still be added together and can
    be "multiplied" with elements of a ring (instead of a field). 
  
