
#+TITLE: Algebra (3)
#+AUTHOR: Vittorio Zaccaria
#+INCLUDE: ./beamer_modern.org
#+LEVEL: 3

#+OPTIONS:   H:3 num:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t ':t


* Algebras of vector spaces and modules
** Vector spaces 

*** Vector space
    
    Set of elements (called *vectors*) which can be added together and multiplied
    by scalars (i.e., elements of a field $K$). So, both addition and scalar
    multiplication should be defined. Subtraction and division come from scalars.

*** Simple vectors

    They are ordered sequences of elements that belong to a field ([[https://en.wikipedia.org/wiki/Scalar_(mathematics)][scalars)]].
    Classical results of geometry apply.

*** Normed vector spaces
    
    A *normed* vector space $V$ is endowed with a map $V \rightarrow R$. 

*** Inner product spaces 
    
    An *inner product* space $V$ is endowed with an operation $V \times V \rightarrow R$.

*** Algebra over a field

    It is a vector space equipped with a bi-linear operator acting as *multiplication* between vectors.

    Examples: 
    
    - $R^3$ with cross-product $\times$

*** Tensor algebra 
   
    Multiplication is just a concatenation of symbols. [[https://en.wikipedia.org/wiki/Algebra_over_a_field][(wikipedia)]]

** Modules 

*** Module

    Generalization of vector space. Elements can still be added together and can
    be "multiplied" with elements of a ring (instead of a field). 
  
